---
default:
  image: docker.io/texlive/texlive:latest
  before_script:
    - latex --version
    - latexmk --version

stages:
  - Build

Generate PDF:
  stage: Build
  script:
    - makeglossaries "thesis"
    - latexmk -bibtex -output-format=pdf -pdf -time thesis.tex
  artifacts:
    paths:
      - thesis.pdf
